In [1]:
import numpy as np


In [5]:
a=np.random.randint(30,99,20)
a

array([65, 96, 48, 72, 53, 81, 71, 48, 53, 52, 38, 53, 50, 66, 68, 74, 34,
       44, 48, 70])

In [7]:
a[-1]

70

In [9]:
a[9]

52

In [11]:
a=np.random.randint(30,99,(8,9))
a

array([[57, 73, 82, 42, 39, 81, 38, 47, 75],
       [65, 48, 64, 81, 44, 90, 97, 60, 53],
       [83, 72, 68, 41, 41, 40, 93, 51, 78],
       [49, 57, 48, 83, 65, 77, 84, 35, 71],
       [94, 78, 97, 73, 32, 76, 48, 41, 89],
       [45, 41, 65, 82, 38, 67, 62, 67, 64],
       [70, 60, 88, 31, 65, 36, 55, 53, 64],
       [62, 57, 60, 80, 31, 89, 60, 89, 73]])

In [19]:
a[1:5]

array([[65, 48, 64, 81, 44, 90, 97, 60, 53],
       [83, 72, 68, 41, 41, 40, 93, 51, 78],
       [49, 57, 48, 83, 65, 77, 84, 35, 71],
       [94, 78, 97, 73, 32, 76, 48, 41, 89]])

In [43]:
a[7,0]

62

NameError: name 't' is not defined

In [25]:
import pandas as pd

In [49]:
k=[[4,7],[2,3],[90,50]]
k

[[4, 7], [2, 3], [90, 50]]

In [80]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  3],
       [90, 50]])

In [82]:
t.ndim


2

In [86]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (3, 2) instead

In [88]:
t

array([[ 4,  7],
       [ 2,  3],
       [90, 50]])

In [106]:
dt=pd.DataFrame(t)
dt

0   1
0   4   7
1   2   3
2  90  50

In [110]:
dt=pd.DataFrame(k,columns=['name','num'],index=[357,358,359])
dt

name  num
357     4    7
358     2    3
359    90   50

In [112]:
dt.num

357     7
358     3
359    50
Name: num, dtype: int64

In [116]:
dt.columns

Index(['name', 'num'], dtype='object')

In [118]:
dt['num'].mode()

0     3
1     7
2    50
Name: num, dtype: int64